# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = /home/aaswenson/depletion/length_25_cm/output/process_$(Cluster)_$(Process).out
error = /home/aaswenson/depletion/length_25_cm/error/process_$(Cluster)_$(Process).err
log = /home/aaswenson/depletion/length_25_cm/log/process_$(Cluster)_$(Process).log
#+IsBuildJob = true
#requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") 

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH= PYTHONPATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = /home/aaswenson/depletion/length_25_cm/send_install_run_mcnp.bash
transfer_input_files = /home/aaswenson/depletion/length_25_cm/mcnp_run_tar_send.bash, /home/aaswenson/depletion/length_25_cm/inputs/$(comp_file)

# Command line arguments for the executable
arguments = $(comp_file)

# Don't send emails
notification = never

# Request resources
request_cpus = 1
request_memory = 300MB
request_disk = 30GB

queue comp_file from input_list.txt