version: 2

jobs:
    test:
        docker:
            - image: pyne/pyne_ubuntu_16.04
        steps:
            - checkout
            - run: pip install pytest numpy scipy
            - run:
                 name: run tests
                 command: |
                     pytest
workflows:
    version: 2
    test:
        jobs:
            - test
