version: 2

jobs:
    test:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout
            - run:
                 name: run tests
                 command: |
                     cd ./optimization
                     pytests
workflows:
    version: 2
    test:
        jobs:
            -test
