version: 2

jobs:
    test:
        docker:
            - image: pyne/pyne_ubuntu_16.04
        steps:
            - checkout
            - run: apt-get update
            - run: apt-get -y install python3-pip
            - run: pip3 install pytest
                 name: run tests
                 command: |
                     pytest
workflows:
    version: 2
    test:
        jobs:
            - test
